# Generated by Django 4.0.1 on 2022-01-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'db_table': 'd_gender',
            },
        ),
        migrations.CreateModel(
            name='DStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status_name', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'd_status',
            },
        ),
        migrations.CreateModel(
            name='DType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'd_type',
            },
        ),
        migrations.CreateModel(
            name='TClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('ok', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('viber', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 't_client',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TDepartment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main.tdepartment')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
                'db_table': 't_department',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TLegalEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('inn', models.CharField(max_length=20)),
                ('kpp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Юр. Лицо',
                'verbose_name_plural': 'Юр. Лица',
                'db_table': 't_legal_entity',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почты',
                'db_table': 't_mail',
            },
        ),
        migrations.CreateModel(
            name='TPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'db_table': 't_phone',
            },
        ),
        migrations.CreateModel(
            name='TSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_socials', to='main.tclient')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Соцниальные сети',
                'db_table': 't_social',
            },
        ),
        migrations.CreateModel(
            name='TLegalEntityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tdepartment')),
                ('id_legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tlegalentity')),
            ],
            options={
                'verbose_name': 'Legal Entity and Department',
                'db_table': 't_legal_entity_department',
            },
        ),
        migrations.CreateModel(
            name='TClientDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.tclient')),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_dept_cl', to='main.tdepartment')),
            ],
            options={
                'verbose_name': 'Client and Department',
                'db_table': 't_client_department',
            },
        ),
        migrations.AddField(
            model_name='tclient',
            name='additional_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_phones', to='main.tphone'),
        ),
        migrations.AddField(
            model_name='tclient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_gender', to='main.dgender'),
        ),
        migrations.AddField(
            model_name='tclient',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_status', to='main.dstatus'),
        ),
        migrations.AddField(
            model_name='tclient',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_mails', to='main.tmail'),
        ),
    ]
