# Generated by Django 4.0.1 on 2022-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tclient_additional_phone_tphone_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tclient',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
