# Generated by Django 4.0.1 on 2022-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tclient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tclient',
            name='id',
            field=models.CharField(blank=True, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
